@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.access_token}}
###

###
# @name create-user
POST {{baseUrl}}/users/create
Content-Type: application/json

{
  "name": "User 333333",
  "email": "1111@gmail.com",
  "password": "fadababaca"
}

###
# @name list-users
GET {{baseUrl}}/users/list

###
# @name list-users-by-email
POST  {{baseUrl}}/users/list-by-email
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email": "diogofaria073@gmail.com"
}

###
# @name authenticate
POST {{baseUrl}}/sessions/create
Content-Type: application/json

{
  "email": "diogofaria073@gmail.com",
  "password": "fadababaca"
}

###
# @name update-user
PUT {{baseUrl}}/users/update
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "id":"c058b844-5f98-44ea-b268-eddf3d8fc372",
  "name": "JAO VINTE3 Lima - Taysa Lima Garcia",
  "email": "jaoXXIII@gmail.com",
  "isActive": true
}