@baseUrl = http://localhost:3000

###

@name = 'create-product''
POST {{baseUrl}}/products/create
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Product 1 description",
  "price": 100
}

###
@name = 'list-products''
GET {{baseUrl}}/products/list