@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.access_token}}
###

# @name create-product
POST {{baseUrl}}/products/create
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Product 1",
  "description": "Product 1 description",
  "price": 100,
  "isAvailable": true
}

###
# @name list-products
GET {{baseUrl}}/products/list


###
# @name create-user
POST {{baseUrl}}/users/create
Content-Type: application/json

{
  "name": "User 1",
  "email": "diogofaria072@gmail.com",
  "password": "fadababaca",
  "isActive": true
}

###
# @name list-users
GET {{baseUrl}}/users/list


###
# @name authenticate
POST {{baseUrl}}/sessions/create
Content-Type: application/json

{
  "email": "diogofaria072@gmail.com",
  "password": "fadababaca"
}